@startuml
skinparam actorStyle awesome 

left to right direction

rectangle DashboardDeVenta {
    usecase "Iniciar sesion" as iniciarSesion
    usecase "Registrar venta" as registrarVenta
    usecase "Generar reportes de ventas al dia/mes" as generarReporteDeVentas
    
    package GestionarEmpleado {
        usecase "Dar de alta a empleado" as darDeAltaEmpleado
        usecase "Ver registros de empleados" as verRegistrosDeEmpleados
        usecase "Filtrar empleados" as filtrarEmpleados
        usecase "Actualizar empleado" as actualizarEmpleado
        usecase "Dar de baja a empleado" as darDeBajaEmpleado
    }
    
    package GestionarCliente {
        usecase "Dar de alta a cliente" as darDeAltaCliente
        usecase "Ver registros de clientes" as verRegistrosDeClientes
        usecase "Filtrar clientes" as filtrarClientes
        usecase "Actualizar cliente" as actualizarCliente
        usecase "Dar de baja a cliente" as darDeBajaCliente
    }
    
    package GestionarCategoria {
        usecase "Crear categoria" as crearCategoria
        usecase "Ver registros de categoria" as verRegistrosDeCategoria
        usecase "Dar de baja a categoria" as darDeBajaCategoria
        usecase "Actualizar categoria" as actualizarCategoria
    
        package GestionarProducto {
            usecase "Crear producto" as guardarProducto
            usecase "Ver registros de productos" as verRegistrosDeProductos
            usecase "Filtrar productos" as filtrarProductos
            usecase "Dar de baja a producto" as darDeBajaProducto
            usecase "Actualizar producto" as actualizarProducto
        }
    }
}
' ================================================= '
actor "Admin 1" as Admin1
actor "Empleado 1" as Empleado1
Empleado1 <|-- Admin1
' ================================================= '
Admin1 -- generarReporteDeVentas 
Empleado1 -- iniciarSesion
Empleado1 -- registrarVenta
' ================================================= '
actor "Admin 2" as Admin2

Admin2 -- darDeAltaEmpleado
Admin2 -- verRegistrosDeEmpleados
Admin2 -- filtrarEmpleados
Admin2 -- actualizarEmpleado
Admin2 -- darDeBajaEmpleado
' ================================================= '
actor "Admin 3" as Admin3
actor "Empleado 3" as Empleado3
Empleado3 <|-- Admin3

actualizarCliente -- Admin3
darDeBajaCliente -- Admin3 
Empleado3 -- darDeAltaCliente
Empleado3 -- verRegistrosDeClientes
Empleado3 -- filtrarClientes
' ================================================= '
actor "Admin 4" as Admin4
actor "Empleado 4" as Empleado4
Empleado4 <|-- Admin4

crearCategoria -- Admin4
Empleado4 -- verRegistrosDeCategoria
darDeBajaCategoria -- Admin4
actualizarCategoria -- Admin4

Empleado4 -- guardarProducto
Empleado4 -- verRegistrosDeProductos
Empleado4 -- filtrarProductos
darDeBajaProducto -- Admin4
Empleado4 -- actualizarProducto
' ================================================= '
@enduml